version: "3.9"

services:
  app:
    image: bridicarlos/goodvideo-upload:1.0
    hostname: goodvideo
    environment:
      - SERVER_PORT=8080
      - DATABASE_URL=jdbc:postgresql://db-postgres:5432/upload
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres   
      - DEFAULT_PATH=/usr/upload/videos 
      - KAFKA_BOOTSTRAP_SERVERS=kafka1:9092
    ports:
      - "8080:8080"    
    depends_on:
      - db-postgres
      - db-redis
      - zookeeper1
      - kafka1
    volumes:
      - /home/bridi/Documents/fiap/videos:/usr/upload/videos
    networks:
      - app-network
  db-postgres:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=upload
    ports:
      - "5432:5432"
    networks:
      - app-network      
  db-redis:
    image: redis:latest
    hostname: redis
    ports:
      - "6379:6379"
  zookeeper1:
      image: confluentinc/cp-zookeeper:7.5.1
      container_name: zookeeper1
      hostname: zookeeper1
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000
        ZOOKEEPER_SERVER_ID: 1
        ZOOKEEPER_SERVERS: "zookeeper1:22888:23888"
      ports:
        - 2181:2181
      networks:
        - app-network
  kafka1:
    image: confluentinc/cp-kafka:7.5.1
    container_name: kafka1
    hostname: kafka1
    restart: always
    depends_on:
      - zookeeper1
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://:29092,OUTSIDE://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:29092,OUTSIDE://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - app-network
networks:
  app-network:
