services:
  app:
    image: bridi/goodvideo-process:latest
    hostname: goodvideo
    environment:
      - SERVER_PORT=8080
      - KAFKA_BOOTSTRAP_SERVERS=host.docker.internal:9092
      - FFMPEG_PATH=/usr/local/bin/ffmpeg
      - DOWNLOAD_PATH=/tmp/dir/%s/download/
      - ZIP_PATH=/tmp/dir/zip/
      - FRAMES_PATH=/tmp/dir/frames/
    ports:
      - "8080:8080"
    networks:
      - app-network
networks:
  app-network:
